name: 'Microservices versioning'
description: 'This actions is about upping versions of each microservice automatically'
author: 'Mostefa Kamal Lala'
inputs:
  pull_number:
    required: true
    description: 'The pull request number'
runs:
  using: 'node12'
  main: 'dist/index.js'
